import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,CheckCircle2,Download,FileUp,Send,ShieldCheck} from 'lucide-react';
const API='http://localhost:8000/api';
const token=()=>localStorage.getItem('token');
export default function StaffDashboard(){
 const [file,setFile]=useState<File|null>(null),[status,setStatus]=useState(''),[result,setResult]=useState<any>(),[me,setMe]=useState<any>();
 useEffect(()=>{fetch(`${API}/auth/me`,{headers:{Authorization:`Bearer ${token()}`}}).then(r=>r.json()).then(setMe).catch(()=>location.href='/login')},[]);
 const upload=async()=>{if(!file)return;setStatus('Uploading and calculating attendance…');setResult(undefined);const body=new FormData();body.append('file',file);try{const r=await fetch(`${API}/attendance/upload`,{method:'POST',headers:{Authorization:`Bearer ${token()}`},body});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Upload failed');setResult(data);setStatus('Import complete. Risks have been evaluated and notifications processed.')}catch(e:any){setStatus(e.message)}};
 return <main className="staff"><header className="staff-head"><Link className="wordmark dark" to="/"><span>✦</span> AttendSure</Link><div><span className="staff-role">{me?.role?.replace('_',' ')}</span><b>{me?.name}</b><button onClick={()=>{localStorage.clear();location.href='/'}}>Sign out</button></div></header><section className="staff-hero"><div><span className="eyebrow">ATTENDANCE OPERATIONS</span><h1>Upload. Evaluate.<br/><em>Notify early.</em></h1><p>Import student attendance and AttendSure recalculates every risk level. Students and parents with a shortage are notified automatically.</p></div><div className="flow"><b>CSV / Excel</b><ArrowRight/><b>Risk calculation</b><ArrowRight/><b><Send size={15}/> WhatsApp</b></div></section><section className="upload-panel"><div className="upload-copy"><span className="eyebrow">STEP 01 — IMPORT</span><h2>Attendance file</h2><p>Required columns: student_id, subject_code, date, status.</p><a href={`${API}/attendance/sample-csv`}>Download sample CSV <Download size={14}/></a></div><label className={'dropzone '+(file?'selected':'')}><FileUp size={30}/><b>{file?file.name:'Choose an attendance file'}</b><small>{file?'Ready to validate and import':'CSV, XLSX or XLS'}</small><input type="file" accept=".csv,.xlsx,.xls" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="import-button" disabled={!file||status.includes('Uploading')} onClick={upload}>{status.includes('Uploading')?'Calculating…':'Import and evaluate'} <ArrowRight size={16}/></button></section>{status&&<div className={'upload-status '+(result?'success':'')}><CheckCircle2 size={19}/>{status}</div>}{result&&<section className="upload-result"><div className="result-head"><div><span className="eyebrow">IMPORT REPORT</span><h2>{result.valid_rows} valid rows processed</h2></div><div className="sent"><Send size={18}/><strong>{result.notification_sent}</strong><span>WhatsApp<br/>messages sent</span></div></div><div className="result-grid"><div><strong>{result.total_rows}</strong><span>Total rows</span></div><div><strong>{result.invalid_rows}</strong><span>Rows needing review</span></div><div><strong>{result.notification_attempts}</strong><span>Delivery attempts</span></div></div>{result.errors?.length>0&&<div className="row-errors"><b>Rows not imported</b>{result.errors.map((x:any)=><p key={x.row}>Row {x.row}: {x.reason}</p>)}</div>}{result.notification_failures?.length>0&&<div className="row-errors"><b>WhatsApp messages that failed</b>{result.notification_failures.map((x:any,i:number)=><p key={i}>{x.to}: {x.error}</p>)}</div>}</section>}<section className="staff-note"><ShieldCheck/><p><b>Notification rule:</b> current attendance below 75%, or a four-week forecast that crosses below 75%. Recipients must have consented to WhatsApp notifications.</p></section></main>
}
